// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mroletidbykedyumfhab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yb2xldGlkYnlrZWR5dW1maGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTU4MDQsImV4cCI6MjA3MzUzMTgwNH0.CF2cU0jlafGgtnoWmfUgs40NJ4IHmpNN0eu9L4nwcyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});